# Generated by Django 4.1.3 on 2022-12-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_remove_pet_trait'),
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='pet',
            field=models.ManyToManyField(related_name='traits', to='pets.pet'),
        ),
    ]
